<template>
  <div id="menus" class="header-padding">
    <!-- 头部导航 -->
    <header class="topnav">
        <router-link to="/" class="backhome"></router-link>
    </header>
    <swiper :options="swiperOption" ref="mySwiper" v-if="show">
        <swiper-slide v-for="(item, index) in swiperSlides">
          <menu-item-list :tempdata="item"></menu-item-list>
        </swiper-slide>
        <div class="swiper-pagination" slot="pagination" ref="pagination"></div>
    </swiper>
  </div>
</template>


<script>
import $ from 'jquery'
import 'swiper/dist/css/swiper.css'
import { swiper, swiperSlide } from 'vue-awesome-swiper'
import MenuItemList from './templet/MenuItemList.vue'
import router from '.././router'
import { LOGOUT,LOGIN } from '.././vuex/mutation_types'
export default {
    name: "Menus",
    data() {
        return {
            show:false,
            tmp1 : [
            {
                "id": 582,
                "menuItemId": 52,
                "type": 14,
                "name": "当季推荐菜",
                "status": 0,
                "iconUrl": "2f1e2b904baa46d2a5876a59268b3b2e.png",
                "menuItemTempletList": [
                    {
                        "id": 5349,
                        "menuItemId": 52,
                        "columnId": 582,
                        "templetType": 1,
                        "templetName": "A版-无菜",
                        "templetImgUrl": "046371a40e6b4b76997f788393e968a6.jpg",
                        "dishQty": 0,
                        "dishInfo": null,
                        "status": 0
                    },
                    {
                        "id": 6389,
                        "menuItemId": 52,
                        "columnId": 582,
                        "templetType": 2,
                        "templetName": "A版-1个菜",
                        "templetImgUrl": "29fa5a54c1ad4080b2c6252d2431f3eb.jpg",
                        "dishQty": 1,
                        "dishInfo": [
                            {
                                "dishItems": [
                                    {
                                        "id": 893,
                                        "itemId": "00000000001536",
                                        "name": "儿童套餐",
                                        "code": "103054",
                                        "keyWord": "ETTC",
                                        "desp": "",
                                        "spec": "",
                                        "unitName": "套",
                                        "itemClassId": "00000000000085",
                                        "tempItemFlg": 0,
                                        "setMealFlg": 0,
                                        "setMealPrType": null,
                                        "price": 19,
                                        "vipPrice": null,
                                        "minAddCnt": 0,
                                        "barCode": "",
                                        "needMakeWay": 0,
                                        "imgUrl": "",
                                        "videoUrl": "",
                                        "recommendImgUrl": "",
                                        "status": 1,
                                        "isUserRecommend": 0,
                                        "dishItemResponses": null,
                                        "showVedio": false,
                                        "isOnSale": true,
                                        "isNotify": 0,
                                        "tasteDesp": null,
                                        "makeTime": null,
                                        "tasteType": null,
                                        "iconUrl": ""
                                    }
                                ],
                                "classId": "",
                                "className": ""
                            }
                        ],
                        "status": 0
                    },
                    {
                        "id": 5318,
                        "menuItemId": 52,
                        "columnId": 582,
                        "templetType": 3,
                        "templetName": "B版-2个菜-1",
                        "templetImgUrl": "49e781156691458e8864879e811ffb6f.jpg",
                        "dishQty": 2,
                        "dishInfo": [
                            {
                                "dishItems": [
                                    {
                                        "id": 2668,
                                        "itemId": "00000000002614",
                                        "name": "香椿豆腐",
                                        "code": "102182",
                                        "keyWord": "XCDF",
                                        "desp": "",
                                        "spec": "",
                                        "unitName": "例",
                                        "itemClassId": "00000000000084",
                                        "tempItemFlg": 0,
                                        "setMealFlg": 0,
                                        "setMealPrType": null,
                                        "price": 36,
                                        "vipPrice": null,
                                        "minAddCnt": 0,
                                        "barCode": "",
                                        "needMakeWay": 0,
                                        "imgUrl": "",
                                        "videoUrl": "",
                                        "recommendImgUrl": "",
                                        "status": 1,
                                        "isUserRecommend": 0,
                                        "dishItemResponses": null,
                                        "showVedio": false,
                                        "isOnSale": true,
                                        "isNotify": 0,
                                        "tasteDesp": null,
                                        "makeTime": null,
                                        "tasteType": null,
                                        "iconUrl": ""
                                    },
                                    {
                                        "id": 2663,
                                        "itemId": "00000000002609",
                                        "name": "鸭丝炒合菜",
                                        "code": "101428",
                                        "keyWord": "YSCHC",
                                        "desp": "",
                                        "spec": "",
                                        "unitName": "例",
                                        "itemClassId": "00000000000083",
                                        "tempItemFlg": 0,
                                        "setMealFlg": 0,
                                        "setMealPrType": null,
                                        "price": 32,
                                        "vipPrice": null,
                                        "minAddCnt": 0,
                                        "barCode": "",
                                        "needMakeWay": 0,
                                        "imgUrl": "",
                                        "videoUrl": "",
                                        "recommendImgUrl": "",
                                        "status": 1,
                                        "isUserRecommend": 0,
                                        "dishItemResponses": null,
                                        "showVedio": false,
                                        "isOnSale": true,
                                        "isNotify": 0,
                                        "tasteDesp": null,
                                        "makeTime": null,
                                        "tasteType": null,
                                        "iconUrl": ""
                                    }
                                ],
                                "classId": "",
                                "className": ""
                            }
                        ],
                        "status": 0
                    },
                    {
                        "id": 5319,
                        "menuItemId": 52,
                        "columnId": 582,
                        "templetType": 3,
                        "templetName": "B版-2个菜-1",
                        "templetImgUrl": "a8970f0e07784cbb8d4250df5fc41ce4.jpg",
                        "dishQty": 2,
                        "dishInfo": [
                            {
                                "dishItems": [
                                    {
                                        "id": 2230,
                                        "itemId": "00000000002115",
                                        "name": "炸香椿鱼儿",
                                        "code": "101262",
                                        "keyWord": "ZXCYE",
                                        "desp": "",
                                        "spec": "",
                                        "unitName": "例",
                                        "itemClassId": "00000000000083",
                                        "tempItemFlg": 0,
                                        "setMealFlg": 0,
                                        "setMealPrType": null,
                                        "price": 32,
                                        "vipPrice": null,
                                        "minAddCnt": 0,
                                        "barCode": "",
                                        "needMakeWay": 0,
                                        "imgUrl": "",
                                        "videoUrl": "",
                                        "recommendImgUrl": "",
                                        "status": 1,
                                        "isUserRecommend": 0,
                                        "dishItemResponses": null,
                                        "showVedio": false,
                                        "isOnSale": true,
                                        "isNotify": 0,
                                        "tasteDesp": null,
                                        "makeTime": null,
                                        "tasteType": null,
                                        "iconUrl": ""
                                    },
                                    {
                                        "id": 2666,
                                        "itemId": "00000000002612",
                                        "name": "炸花椒芽",
                                        "code": "101431",
                                        "keyWord": "ZHJY",
                                        "desp": "",
                                        "spec": "",
                                        "unitName": "例",
                                        "itemClassId": "00000000000083",
                                        "tempItemFlg": 0,
                                        "setMealFlg": 0,
                                        "setMealPrType": null,
                                        "price": 32,
                                        "vipPrice": null,
                                        "minAddCnt": 0,
                                        "barCode": "",
                                        "needMakeWay": 0,
                                        "imgUrl": "",
                                        "videoUrl": "",
                                        "recommendImgUrl": "",
                                        "status": 1,
                                        "isUserRecommend": 0,
                                        "dishItemResponses": null,
                                        "showVedio": false,
                                        "isOnSale": true,
                                        "isNotify": 0,
                                        "tasteDesp": null,
                                        "makeTime": null,
                                        "tasteType": null,
                                        "iconUrl": ""
                                    }
                                ],
                                "classId": "",
                                "className": ""
                            }
                        ],
                        "status": 0
                    },
                    {
                        "id": 5320,
                        "menuItemId": 52,
                        "columnId": 582,
                        "templetType": 3,
                        "templetName": "B版-2个菜-1",
                        "templetImgUrl": "aa20f91740fc4948b9037cb343a0a547.jpg",
                        "dishQty": 2,
                        "dishInfo": [
                            {
                                "dishItems": [
                                    {
                                        "id": 2664,
                                        "itemId": "00000000002610",
                                        "name": "荠菜春笋",
                                        "code": "101429",
                                        "keyWord": "QCCS",
                                        "desp": "",
                                        "spec": "",
                                        "unitName": "例",
                                        "itemClassId": "00000000000083",
                                        "tempItemFlg": 0,
                                        "setMealFlg": 0,
                                        "setMealPrType": null,
                                        "price": 38,
                                        "vipPrice": null,
                                        "minAddCnt": 0,
                                        "barCode": "",
                                        "needMakeWay": 0,
                                        "imgUrl": "",
                                        "videoUrl": "",
                                        "recommendImgUrl": "",
                                        "status": 1,
                                        "isUserRecommend": 0,
                                        "dishItemResponses": null,
                                        "showVedio": false,
                                        "isOnSale": true,
                                        "isNotify": 0,
                                        "tasteDesp": null,
                                        "makeTime": null,
                                        "tasteType": null,
                                        "iconUrl": ""
                                    },
                                    {
                                        "id": 2667,
                                        "itemId": "00000000002613",
                                        "name": "水饺（荠菜）",
                                        "code": "103108",
                                        "keyWord": "SJQC",
                                        "desp": "",
                                        "spec": "",
                                        "unitName": "例",
                                        "itemClassId": "00000000000085",
                                        "tempItemFlg": 0,
                                        "setMealFlg": 0,
                                        "setMealPrType": null,
                                        "price": 42,
                                        "vipPrice": null,
                                        "minAddCnt": 0,
                                        "barCode": "",
                                        "needMakeWay": 0,
                                        "imgUrl": "",
                                        "videoUrl": "",
                                        "recommendImgUrl": "",
                                        "status": 1,
                                        "isUserRecommend": 0,
                                        "dishItemResponses": null,
                                        "showVedio": false,
                                        "isOnSale": true,
                                        "isNotify": 0,
                                        "tasteDesp": null,
                                        "makeTime": null,
                                        "tasteType": null,
                                        "iconUrl": ""
                                    }
                                ],
                                "classId": "",
                                "className": ""
                            }
                        ],
                        "status": 0
                    }
                ]
                },
                {
                    "id": 558,
                    "menuItemId": 52,
                    "type": 2,
                    "name": "烤鸭",
                    "status": 0,
                    "iconUrl": "552c7b9f1aa64cfd841f5ea27d4fa68e.png",
                    "menuItemTempletList": [
                        {
                            "id": 4884,
                            "menuItemId": 52,
                            "columnId": 558,
                            "templetType": 2,
                            "templetName": "A版-1个菜",
                            "templetImgUrl": "e2167102793d47f9b9a54d77af1e6262.jpg",
                            "dishQty": 1,
                            "dishInfo": [
                                {
                                    "dishItems": [
                                        {
                                            "id": 432,
                                            "itemId": "00000000001016",
                                            "name": "锣鼓烤鸭",
                                            "code": "105001",
                                            "keyWord": "LGKY",
                                            "desp": "",
                                            "spec": "",
                                            "unitName": "套",
                                            "itemClassId": "00000000000087",
                                            "tempItemFlg": 0,
                                            "setMealFlg": 0,
                                            "setMealPrType": null,
                                            "price": 239,
                                            "vipPrice": null,
                                            "minAddCnt": 0,
                                            "barCode": "",
                                            "needMakeWay": 0,
                                            "imgUrl": "289d978dc0964ad09b5227443b36a89f.jpg",
                                            "videoUrl": "",
                                            "recommendImgUrl": "",
                                            "status": 1,
                                            "isUserRecommend": 0,
                                            "dishItemResponses": null,
                                            "showVedio": false,
                                            "isOnSale": true,
                                            "isNotify": 0,
                                            "tasteDesp": null,
                                            "makeTime": null,
                                            "tasteType": null,
                                            "iconUrl": ""
                                        }
                                    ],
                                    "classId": "",
                                    "className": ""
                                }
                            ],
                            "status": 0
                        },
                        {
                            "id": 4885,
                            "menuItemId": 52,
                            "columnId": 558,
                            "templetType": 2,
                            "templetName": "A版-1个菜",
                            "templetImgUrl": "70a210fcaaf04bb4bf213d249b59241c.jpg",
                            "dishQty": 1,
                            "dishInfo": [
                                {
                                    "dishItems": [
                                        {
                                            "id": 433,
                                            "itemId": "00000000001017",
                                            "name": "挂炉烤鸭",
                                            "code": "105002",
                                            "keyWord": "GLKY",
                                            "desp": "",
                                            "spec": "",
                                            "unitName": "套",
                                            "itemClassId": "00000000000087",
                                            "tempItemFlg": 0,
                                            "setMealFlg": 0,
                                            "setMealPrType": null,
                                            "price": 198,
                                            "vipPrice": 118,
                                            "minAddCnt": 0,
                                            "barCode": "",
                                            "needMakeWay": 0,
                                            "imgUrl": "d0f971ae419a435692d44c1fde388c5f.jpg",
                                            "videoUrl": "",
                                            "recommendImgUrl": "",
                                            "status": 1,
                                            "isUserRecommend": 0,
                                            "dishItemResponses": [
                                                {
                                                    "id": 433,
                                                    "itemId": "00000000001017",
                                                    "name": "挂炉烤鸭",
                                                    "code": "105002",
                                                    "keyWord": "GLKY",
                                                    "desp": "",
                                                    "spec": "",
                                                    "unitName": "套",
                                                    "itemClassId": "00000000000087",
                                                    "tempItemFlg": 0,
                                                    "setMealFlg": 0,
                                                    "setMealPrType": null,
                                                    "price": 198,
                                                    "vipPrice": 118,
                                                    "minAddCnt": 0,
                                                    "barCode": "",
                                                    "needMakeWay": 0,
                                                    "imgUrl": "d0f971ae419a435692d44c1fde388c5f.jpg",
                                                    "videoUrl": "",
                                                    "recommendImgUrl": "",
                                                    "status": 1,
                                                    "isUserRecommend": 0,
                                                    "dishItemResponses": null,
                                                    "showVedio": false,
                                                    "isOnSale": true,
                                                    "isNotify": 0,
                                                    "tasteDesp": null,
                                                    "makeTime": null,
                                                    "tasteType": null,
                                                    "iconUrl": null
                                                },
                                                {
                                                    "id": 434,
                                                    "itemId": "00000000001018",
                                                    "name": "挂炉烤鸭（半套）",
                                                    "code": "105003",
                                                    "keyWord": "GLKYBT",
                                                    "desp": "",
                                                    "spec": "",
                                                    "unitName": "套（半）",
                                                    "itemClassId": "00000000000087",
                                                    "tempItemFlg": 0,
                                                    "setMealFlg": 0,
                                                    "setMealPrType": null,
                                                    "price": 125,
                                                    "vipPrice": null,
                                                    "minAddCnt": 0,
                                                    "barCode": "",
                                                    "needMakeWay": 0,
                                                    "imgUrl": "53fc973be9684bd5a8bf0184a03948bb.jpg",
                                                    "videoUrl": "",
                                                    "recommendImgUrl": "",
                                                    "status": 1,
                                                    "isUserRecommend": 0,
                                                    "dishItemResponses": null,
                                                    "showVedio": false,
                                                    "isOnSale": true,
                                                    "isNotify": 0,
                                                    "tasteDesp": null,
                                                    "makeTime": null,
                                                    "tasteType": null,
                                                    "iconUrl": null
                                                },
                                                {
                                                    "id": 435,
                                                    "itemId": "00000000001019",
                                                    "name": "白砂糖",
                                                    "code": "105004",
                                                    "keyWord": "BST",
                                                    "desp": "",
                                                    "spec": "",
                                                    "unitName": "例（砂糖）",
                                                    "itemClassId": "00000000000087",
                                                    "tempItemFlg": 0,
                                                    "setMealFlg": 0,
                                                    "setMealPrType": null,
                                                    "price": 6,
                                                    "vipPrice": null,
                                                    "minAddCnt": 0,
                                                    "barCode": "",
                                                    "needMakeWay": 0,
                                                    "imgUrl": "",
                                                    "videoUrl": "",
                                                    "recommendImgUrl": "",
                                                    "status": 1,
                                                    "isUserRecommend": 0,
                                                    "dishItemResponses": null,
                                                    "showVedio": false,
                                                    "isOnSale": true,
                                                    "isNotify": 0,
                                                    "tasteDesp": null,
                                                    "makeTime": null,
                                                    "tasteType": null,
                                                    "iconUrl": null
                                                },
                                                {
                                                    "id": 436,
                                                    "itemId": "00000000001020",
                                                    "name": "荷叶饼（鸭饼）",
                                                    "code": "105005",
                                                    "keyWord": "HYBYB",
                                                    "desp": "",
                                                    "spec": "",
                                                    "unitName": "例（鸭饼）",
                                                    "itemClassId": "00000000000087",
                                                    "tempItemFlg": 0,
                                                    "setMealFlg": 0,
                                                    "setMealPrType": null,
                                                    "price": 13,
                                                    "vipPrice": null,
                                                    "minAddCnt": 0,
                                                    "barCode": "",
                                                    "needMakeWay": 0,
                                                    "imgUrl": "",
                                                    "videoUrl": "",
                                                    "recommendImgUrl": "",
                                                    "status": 1,
                                                    "isUserRecommend": 0,
                                                    "dishItemResponses": null,
                                                    "showVedio": false,
                                                    "isOnSale": true,
                                                    "isNotify": 0,
                                                    "tasteDesp": null,
                                                    "makeTime": null,
                                                    "tasteType": null,
                                                    "iconUrl": null
                                                },
                                                {
                                                    "id": 437,
                                                    "itemId": "00000000001021",
                                                    "name": "葱丝",
                                                    "code": "105006",
                                                    "keyWord": "CS",
                                                    "desp": "",
                                                    "spec": "",
                                                    "unitName": "例（葱丝）",
                                                    "itemClassId": "00000000000087",
                                                    "tempItemFlg": 0,
                                                    "setMealFlg": 0,
                                                    "setMealPrType": null,
                                                    "price": 6,
                                                    "vipPrice": null,
                                                    "minAddCnt": 0,
                                                    "barCode": "",
                                                    "needMakeWay": 0,
                                                    "imgUrl": "",
                                                    "videoUrl": "",
                                                    "recommendImgUrl": "",
                                                    "status": 1,
                                                    "isUserRecommend": 0,
                                                    "dishItemResponses": null,
                                                    "showVedio": false,
                                                    "isOnSale": true,
                                                    "isNotify": 0,
                                                    "tasteDesp": null,
                                                    "makeTime": null,
                                                    "tasteType": null,
                                                    "iconUrl": null
                                                },
                                                {
                                                    "id": 438,
                                                    "itemId": "00000000001022",
                                                    "name": "甜面酱",
                                                    "code": "105007",
                                                    "keyWord": "TMJ",
                                                    "desp": "",
                                                    "spec": "",
                                                    "unitName": "例（鸭酱）",
                                                    "itemClassId": "00000000000087",
                                                    "tempItemFlg": 0,
                                                    "setMealFlg": 0,
                                                    "setMealPrType": null,
                                                    "price": 6,
                                                    "vipPrice": null,
                                                    "minAddCnt": 0,
                                                    "barCode": "",
                                                    "needMakeWay": 0,
                                                    "imgUrl": "http://juqiimg.beijingjuqi.com/1595bcff60034112aa307f93f8a1b555.jpg",
                                                    "videoUrl": "",
                                                    "recommendImgUrl": "",
                                                    "status": 1,
                                                    "isUserRecommend": 0,
                                                    "dishItemResponses": null,
                                                    "showVedio": false,
                                                    "isOnSale": true,
                                                    "isNotify": 0,
                                                    "tasteDesp": null,
                                                    "makeTime": null,
                                                    "tasteType": null,
                                                    "iconUrl": null
                                                },
                                                {
                                                    "id": 439,
                                                    "itemId": "00000000001023",
                                                    "name": "黄瓜条",
                                                    "code": "105008",
                                                    "keyWord": "HGT",
                                                    "desp": "",
                                                    "spec": "",
                                                    "unitName": "例（瓜条）",
                                                    "itemClassId": "00000000000087",
                                                    "tempItemFlg": 0,
                                                    "setMealFlg": 0,
                                                    "setMealPrType": null,
                                                    "price": 6,
                                                    "vipPrice": null,
                                                    "minAddCnt": 0,
                                                    "barCode": "",
                                                    "needMakeWay": 0,
                                                    "imgUrl": "",
                                                    "videoUrl": "",
                                                    "recommendImgUrl": "",
                                                    "status": 1,
                                                    "isUserRecommend": 0,
                                                    "dishItemResponses": null,
                                                    "showVedio": false,
                                                    "isOnSale": true,
                                                    "isNotify": 0,
                                                    "tasteDesp": null,
                                                    "makeTime": null,
                                                    "tasteType": null,
                                                    "iconUrl": null
                                                },
                                                {
                                                    "id": 541,
                                                    "itemId": "00000000001125",
                                                    "name": "鸭架汤",
                                                    "code": "101055",
                                                    "keyWord": "YJT",
                                                    "desp": "",
                                                    "spec": "",
                                                    "unitName": "例（鸭汤）",
                                                    "itemClassId": "00000000000083",
                                                    "tempItemFlg": 0,
                                                    "setMealFlg": 0,
                                                    "setMealPrType": null,
                                                    "price": 0,
                                                    "vipPrice": null,
                                                    "minAddCnt": 0,
                                                    "barCode": "",
                                                    "needMakeWay": 0,
                                                    "imgUrl": "",
                                                    "videoUrl": "",
                                                    "recommendImgUrl": "",
                                                    "status": 1,
                                                    "isUserRecommend": 0,
                                                    "dishItemResponses": null,
                                                    "showVedio": false,
                                                    "isOnSale": true,
                                                    "isNotify": 0,
                                                    "tasteDesp": null,
                                                    "makeTime": null,
                                                    "tasteType": null,
                                                    "iconUrl": null
                                                },
                                                {
                                                    "id": 542,
                                                    "itemId": "00000000001126",
                                                    "name": "椒盐鸭架",
                                                    "code": "101056",
                                                    "keyWord": "JYYJ",
                                                    "desp": "",
                                                    "spec": "",
                                                    "unitName": "例（椒盐）",
                                                    "itemClassId": "00000000000083",
                                                    "tempItemFlg": 0,
                                                    "setMealFlg": 0,
                                                    "setMealPrType": null,
                                                    "price": 10,
                                                    "vipPrice": null,
                                                    "minAddCnt": 0,
                                                    "barCode": "",
                                                    "needMakeWay": 0,
                                                    "imgUrl": "http://juqiimg.beijingjuqi.com/5925118d85c7488fb5293fcaab96aca8.jpg",
                                                    "videoUrl": "",
                                                    "recommendImgUrl": "",
                                                    "status": 1,
                                                    "isUserRecommend": 0,
                                                    "dishItemResponses": null,
                                                    "showVedio": false,
                                                    "isOnSale": true,
                                                    "isNotify": 0,
                                                    "tasteDesp": null,
                                                    "makeTime": null,
                                                    "tasteType": null,
                                                    "iconUrl": null
                                                }
                                            ],
                                            "showVedio": false,
                                            "isOnSale": true,
                                            "isNotify": 0,
                                            "tasteDesp": null,
                                            "makeTime": null,
                                            "tasteType": null,
                                            "iconUrl": ""
                                        }
                                    ],
                                    "classId": "",
                                    "className": ""
                                }
                            ],
                            "status": 0
                        },
                        {
                            "id": 4886,
                            "menuItemId": 52,
                            "columnId": 558,
                            "templetType": 2,
                            "templetName": "A版-1个菜",
                            "templetImgUrl": "bd5f09e1d52c42f9af90a9439b73e049.jpg",
                            "dishQty": 1,
                            "dishInfo": [
                                {
                                    "dishItems": [
                                        {
                                            "id": 1884,
                                            "itemId": "00000000001693",
                                            "name": "三星拜寿",
                                            "code": "102100",
                                            "keyWord": "SXBS",
                                            "desp": "",
                                            "spec": "",
                                            "unitName": "例",
                                            "itemClassId": "00000000000084",
                                            "tempItemFlg": 0,
                                            "setMealFlg": 0,
                                            "setMealPrType": null,
                                            "price": 298,
                                            "vipPrice": null,
                                            "minAddCnt": 0,
                                            "barCode": "",
                                            "needMakeWay": 0,
                                            "imgUrl": "586a7eaff2d04471b73386ea0d48a4ea.jpg",
                                            "videoUrl": "",
                                            "recommendImgUrl": "",
                                            "status": 1,
                                            "isUserRecommend": 0,
                                            "dishItemResponses": null,
                                            "showVedio": false,
                                            "isOnSale": true,
                                            "isNotify": 0,
                                            "tasteDesp": null,
                                            "makeTime": null,
                                            "tasteType": null,
                                            "iconUrl": ""
                                        }
                                    ],
                                    "classId": "",
                                    "className": ""
                                }
                            ],
                            "status": 0
                        }
                    ]
                },
            ],
            swiperSlides:[],
            swiperOption: {
              pagination: {
                    el: '.swiper-pagination',
                    clickable: true,
                    renderBullet: function (index, className) {
                        return '<span class="' + className + '"><img src="img/menu-1.png" class="navimg' + index + '" /></span>';
                    },
              },
            },
        }
    },
    components: {
        swiper,
        swiperSlide,
        MenuItemList,
    },
    computed: {
      swiper() {
        return this.$refs.mySwiper.swiper
      }
    },
    mounted() {
        var that = this;
        that.swiperSlides = that.tmp1;
        that.swiperOption = {
          pagination: {
                el: '.swiper-pagination',
                clickable: true,
                renderBullet: function (index, className) {
                    return '<span class="' + className + '"><img src="http://sstt.img.beijingjuqi.com/' + that.tmp1[index].iconUrl + '" /></span>';
                },
          },
        };
        that.show = true;
    },
    methods: {
        
    }
}
</script>